version: 0.17.0.{build}

os: Visual Studio 2017

configuration:
  - Debug
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore src\WAYWF.sln

build:
  parallel: true
  project: src\WAYWF.sln
  verbosity: minimal