<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<GlobalPackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</GlobalPackageReference>
		<GlobalPackageReference Include="WTG.Analyzers" Version="3.7.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</GlobalPackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageVersion Include="System.Collections.Immutable" Version="10.0.10" />
	</ItemGroup>
</Project>
