<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net462</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WAYWF.Agent.Data\WAYWF.Agent.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="IL\ILReader.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ILReader.g.cs</LastGenOutput>
    </Content>
    <Compile Update="IL\ILReader.g.cs">
      <DependentUpon>ILReader.tt</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>
</Project>