<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Prefer32Bit>true</Prefer32Bit>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <Import Project="..\WAYWF.Agent.Shared\WAYWF.Agent.Shared.projitems" Label="Shared" />
  <Import Project="..\WAYWF.Options\WAYWF.Options.projitems" Label="Shared" />
  <ItemGroup>
    <ProjectReference Include="..\WAYWF.Agent.Core\WAYWF.Agent.Core.csproj" />
  </ItemGroup>
</Project>