<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\WAYWF.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\*.*" />
    <Resource Include="Resources\*.*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="waywf.xslt">
      <LogicalName>WAYWF.UI.Resources.waywf.xslt</LogicalName>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <ProjectReference Include="..\WAYWF.Api\WAYWF.Api.csproj" />
    <None Update="waywf.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>