<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Metadata\Type\MetaKnownType.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MetaKnownType.g.cs</LastGenOutput>
    </None>
    <Compile Update="Metadata\Type\MetaKnownType.g.cs">
      <DependentUpon>MetaKnownType.tt</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>
</Project>